# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'myacr001.azurecr.io/hello-node:$(build.buildId)'
  imageNameLatest: 'myacr001.azurecr.io/hello-node:latest'
  
steps:
###- script: docker build -f Dockerfile -t $(imageName) .
###  displayName: 'docker build'
###- script: |
###    docker login -u $(dockerId) -p $(pswd) $(dockerid).azurecr.io
###    docker push $(imageName)
###  displayName: 'docker push'

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    imageName: 'myacr001.azurecr.io/hello-node:$(build.buildId)'
- task: Docker@1
  displayName: Login
  inputs:
    azureSubscriptionEndpoint: 'MyACRConnection'
    azureContainerRegistry: myacr001.azurecr.io
    command: login
- task: Docker@1
  displayName: 'Push an image'
  inputs:
    command: 'push'
    imageName: 'myacr001.azurecr.io/hello-node:$(build.buildId)'
- script: docker tag $(imageName) $(imageNameLatest)
  displayName: 'docker tag'
- task: Docker@1
  displayName: 'Push an image latest'
  inputs:
    command: 'push'
    imageName: 'myacr001.azurecr.io/hello-node:latest'
